### ISSUE TITLE
Consider adding license file(s)

### ISSUE THREAD

**Issue by yupferris** [diwic/splitmut-rs#2]
First of all, nice little crate you've got here :) . I ran into an _exact_ case where this would be useful last night, and had to do some janky stuff to get around it. Now I can just use this and not have to put forth significant effort. Nice!

My only issue is that there's no license info in the project repo, except for in `Cargo.toml` and on crates.io. Was this intended? I'm not sure the implications of distributing code without such licenses, but my ultra-conservative-license-spidey-senses are tingling about it, so I would recommend adding those files :)

**Comment by yupferris** [comment]
Also I wouldn't mind forking and throwing them up there for you if you just don't feel like doing it, hehe.

**Comment by yupferris** [comment]
In particular with Apache 2.0, I believe you're required to reproduce the license files with your source [re]distributions, as it says [here](http://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN) (see the "It requires you to" point, where it says "include a copy of the license in any redistribution you may make that includes Apache software"). I believe the same is the case with MIT.

**Comment by diwic** [comment]
Oh, I've just been sloppy. Added now to please your senses :-)

**Comment by yupferris** [comment]
Lovely, thanks a bunch!
