### ISSUE TITLE
primitive.slice.split_at_mut for slicing at many places

### ISSUE THREAD

**Issue by Eh2406** [diwic/splitmut-rs#3]
Hi,

I have a list of idx to cut a slice. I.E. [10,15,30] and I want [&mut slice[..10], &mut slice[10 .. 15], &mut slice[15 .. 30], &mut slice[30 .. ]]
When I realized it was not in std I looked on crates.io. Figuring someone may have done it for me, and if not I could post it. You have the perfect crate name for this function, and it is not entirely unrelated to your existing utill. Can I write it up and make a pr, or wood you prefer I make my own crate?

Don't get me wrong either way is ok with me :-) One crate with your excellent name will be ez to find. But 2 crates will be each more focused.

Best!

**Comment by diwic** [comment]
You can't return a slice. You can either box it, or return an iterator. Returning an iterator is the better solution IMO, but then I think your suggestion belongs to the Itertools crate rather than mine. In fact, I think you can make one with just a few lines of code using `Itertools::Batching`.

**Comment by Eh2406** [comment]
Hi, Thanks for the comments! I had bean thinking of returning an iterator.

I don't think `Itertools::Batching` helps. If I `Itertools::Batching` over the Idxs than I don't need to skip. If I iterate over the slice then I can not take a new `&mut` to it. 

My idea has gotten muddled in my head. I thought I had two use cases, but on closer inspection I do not. One ternes out not to need `&mut` and the other is easier to solve as a kind of group by. I implemented something like `Itertools::GroupBy` but instead of taking and `iter T` and returning a `iter of Vec[T]` it takes a `&'a mut [T]` and returns a `iter of &'a mut [T]`. This is a slight win as it does not need to allocate Vecs.

I still think that there is a widely useful generalization of split_at_mut, but it is hard to get right in my head with such slippery use cases.

Thanks for your advice.

**Comment by diwic** [comment]
> I don't think Itertools::Batching helps.

You're probably right. Scratch that idea, then. 

> I still think that there is a widely useful generalization of split_at_mut, but it is hard to get right in my head

Maybe it needs to be like chunks_mut (which is in std), but with a variable chunk size (so the chunk sizes come from an iterator)? Something like this:

```
struct ChunksMut<'a, T>(&'a mut [T]);
fn chunks_mut<I: Iterator<Item=usize>, T>(i: I, a: &mut [T]) -> ChunksMut<'a, T> { /* ... */ }
impl<'a, T> Iterator for ChunksMut<'a, T> {
     type Item = &'a mut [T];
}
```

**Comment by Eh2406** [comment]
So something like:

```
struct ChunksMutIter<'a, T: 'a, I: Iterator<Item = usize>> {
    slice: &'a mut [T],
    last_cut: usize,
    next_cut: I,
}

impl<'a, T: 'a, I: Iterator<Item = usize>> Iterator for ChunksMutIter<'a, T, I> {
    type Item = &'a mut [T];
    fn next(&mut self) -> Option<&'a mut [T]> {
        use std::mem;
        match self.next_cut.next() {
            None => {
                if self.slice.is_empty() {
                    None
                } else {
                    Some(mem::replace(&mut self.slice, &mut []))
                }
            }
            Some(x) => {
                let last = self.last_cut;
                self.last_cut = x;
                let s = mem::replace(&mut self.slice, &mut []);
                let (l, r) = s.split_at_mut(last - x);
                self.slice = r;
                Some(l)
            }
        }
    }
}
```

I have not yet tested it.

**Comment by diwic** [comment]
Yup, something like that. I think it could be a valuable addition to itertools (if the maintainers of that crate agree).

You're also right about one other thing. Maybe splitmut is not the right name for this crate as it is more about "multiple distinct mutable references" rather than splitting slices. A generalization of what my crate does would be something else, something like [this](https://github.com/diwic/splitmut-rs/commit/3c412163f9712a088c82969c547e2b0d50b5d6c7).

**Comment by Eh2406** [comment]
Than you so much for the advice and the commentary. Next time I have a clear use case I will talk to itertools.

Thanks again.
